;; CUSTOM SETTINGS OF EMACS VARIABLES BELOW

(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ac-modes (quote (emacs-lisp-mode lisp-interaction-mode c-mode cc-mode c++-mode clojure-mode java-mode perl-mode cperl-mode python-mode ruby-mode ecmascript-mode javascript-mode js-mode js2-mode php-mode css-mode makefile-mode sh-mode fortran-mode f90-mode ada-mode xml-mode sgml-mode haml-mode sass-mode)))
 '(ac-quick-help-delay 1.0)
 '(coffee-js-mode (quote javascript-mode))
 '(coffee-tab-width 2)
 '(custom-safe-themes (quote ("fc5fcb6f1f1c1bc01305694c59a1a861b008c534cae8d0e48e4d5e81ad718bc6" default)))
 '(debug-on-error nil)
 '(face-font-family-alternatives (quote (nil)))
 '(flx-ido-mode t)
 '(flx-ido-threshhold 10000)
 '(font-use-system-font t)
 '(global-auto-complete-mode t)
 '(global-linum-mode t)
 '(hscroll-margin 1)
 '(indent-tabs-mode nil)
 '(inferior-lisp-program "clj-env-dir")
 '(inhibit-startup-screen t)
 '(js-enabled-frameworks (quote (javascript)))
 '(js-indent-level 2)
 '(js-js-switch-tabs nil)
 '(js2-auto-indent-p t)
 '(js2-bounce-indent-p nil)
 '(mf-display-padding-height 48)
 '(mouse-wheel-scroll-amount (quote (1 ((shift) . 1) ((control)))))
 '(mumamo-indent-widen-per-major (quote ((nxhtml-mode ((html-mumamo-mode nxhtml-mumamo-mode))) (html-mode ((html-mumamo-mode nxhtml-mumamo-mode))))))
 '(ns-alternate-modifier (quote meta))
 '(ns-antialias-text t)
 '(ns-command-modifier (quote control))
 '(ns-control-modifier nil)
 '(ns-right-alternate-modifier (quote meta))
 '(nxhtml-default-encoding (quote utf-8))
 '(rails-ws:default-server-type "webrick")
 '(safe-local-variable-values (quote ((encoding . utf-8) (require-final-newline))))
 '(scroll-bar-mode nil)
 '(sieve-manage-default-user "alex@alecnmk.com")
 '(small-temporary-file-directory nil)
 '(stack-trace-on-error nil)
 '(standard-indent 2)
 '(tab-always-indent (quote always))
 '(tab-width 2)
 '(tabbar-auto-scroll-flag nil)
 '(tabbar-background-color "#52676f")
 '(tabbar-cycle-scope (quote tabs))
 '(tabbar-home-button (quote (("[o]") "[x]")))
 '(tabbar-mode t nil (tabbar))
 '(tabbar-mwheel-mode t nil (tabbar))
 '(tabbar-scroll-left-button (quote (("<") "=")))
 '(tabbar-scroll-right-button (quote ((">") "=")))
 '(tabbar-separator (quote ("|")))
 '(tabbar-use-images nil)
 '(tool-bar-mode nil)
 '(yas/global-mode t nil (yasnippet))
 '(yas/root-directory "~/.emacs.d/snippets" nil (yasnippet))
 '(yas/trigger-key "<M-tab>"))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:inherit nil :stipple nil :background "#141414" :foreground "#F8F8F8" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 120 :width normal :foundry "apple" :family "Monaco"))))
 '(button ((((supports :underline t)) (:underline t))))
 '(diff-added ((t (:inherit diff-changed))))
 '(diff-indicator-added ((t (:inherit diff-added :foreground "green"))) t)
 '(diff-indicator-removed ((t (:inherit diff-removed :foreground "red"))) t)
 '(diff-removed ((t (:inherit diff-changed))))
 '(egg-header ((t (:inherit variable-pitch :weight bold :height 1.1))) t)
 '(font-lock-warning-face ((t (:foreground "red"))))
 '(fringe ((t nil)))
 '(header-line ((default (:inherit mode-line)) (((class color grayscale) (background dark)) (:background "grey20" :foreground "grey90" :box nil))))
 '(ns-working-text-face ((t (:underline t))))
 '(scroll-bar ((t nil)))
 '(tabbar-button ((t (:background "#0a2832" :foreground "black"))))
 '(tabbar-button-face ((t (:inherit tabbar-default-face :foreground "green"))) t)
 '(tabbar-button-highlight ((default nil) (nil nil)))
 '(tabbar-default ((t (:background "black" :foreground "green" :inverse-video nil :width normal))))
 '(tabbar-default-face ((t (:inherit nil :background "black" :foreground "blue" :height 0.8))) t)
 '(tabbar-highlight ((t (:background "#0a2832" :foreground "magenta" :inverse-video t :weight bold))))
 '(tabbar-selected ((t (:inherit nil :background "white" :foreground "green" :weight bold))))
 '(tabbar-selected-face ((t (:inherit tabbar-default-face :foreground "gray40"))) t)
 '(tabbar-separator ((t (:inherit tabbar-default :background "black" :foreground "#52676f"))))
 '(tabbar-unselected ((t (:inherit tabbar-default :background "black" :foreground "yellow"))))
 '(tabbar-unselected-face ((t (:inherit tabbar-default-face :background "black"))) t)
 '(vertical-border ((nil nil)))
 '(yas/field-highlight-face ((t (:foreground "blue")))))
